name: Docker-K8s CI/CD Pipeline 
on:
  push:
jobs:
  docker_1:
    runs-on: 
      labels: k8s_master
    steps:
      - name: Set up QEMU test
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qod:actions2
  deploy:
    needs: docker_1
    name: k8s deployment 
    runs-on: 
      labels: k8s_master
    steps:
    #  - name: clone
    #    run:  git clone https://github.com/HarshalST/dockerfile_for_jenkins
      - name: replace image
        run:  sed -i 's,docker.io/httpd,${{ secrets.DOCKERHUB_USERNAME }}/qod:actions2,' **/deployment.yaml
      - name: create deployment
        run: kubectl apply -f **/deployment.yaml --kubeconfig=/tmp/myconfig  
